NID_INVALID_MSG           = 'NID value is invalid'
NID_ONLY_ZEROES_MSG       = 'NID value cannot contain only zeroes'
NID_NO_ZERO_START_MSG     = 'NID value cannot start with zero'
NID_WRONG_LENGTH_MSG      = 'NID value has wrong length'
NID_NON_NUMERIC_MSG       = 'NID value contains non-numeric content'
NID_NON_NUMERIC_CHECK_MSG = 'NID value non-numeric check digit'
